[metadata]
name = doffpe
version = 0.1.0
author = Theragen Bio
author_email = deepomics.ffpe@theragenbio.com
description = "DEEPOMICS FFPE PLUS is a deep learning-based pipeline designed to remove FFPE artifacts and retain true somatic variants for client data analysis"
long_description = file: README.md
long_description_content_type = text/markdown
url = https://github.com/theragenbio/deepomics-ffpe
license = Proprietary
license_files = LICENSE
classifiers =
    Programming Language :: Python :: 3
    License :: Other/Proprietary License
    Operating System :: POSIX :: Linux

[options]
packages = find:
python_requires = >=3.7

