#!/bin/bash

# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
__conda_setup="$('$HOME/miniconda3_doffpe/bin/conda' 'shell.bash' 'hook' 2> /dev/null)"
if [ $? -eq 0 ]; then
    eval "$__conda_setup"
else
    if [ -f "$HOME/miniconda3_doffpe/etc/profile.d/conda.sh" ]; then
        . "$HOME/miniconda3_doffpe/etc/profile.d/conda.sh"
    else
        export PATH="$HOME/miniconda3_doffpe/bin:$PATH"
    fi
fi
unset __conda_setup
# <<< conda initialize <<<

conda activate doffpe
#conda info

SCRIPT_PATH="$(readlink -f "$0")"
SCRIPT_DIR="$(dirname "$SCRIPT_PATH")"
SCRIPT="$SCRIPT_DIR/doffpe_client.py"
python "$SCRIPT" "$@"
